# Generated by Django 4.1.6 on 2023-02-06 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='content',
            new_name='name',
        ),
    ]
